export const MOCK_DATA = [
  {
    id: 0,
    name: '마라탕 & 꿔바로우',
    amount: 59000,
    type: 'expense',
    category: '🍚 식비',
    date: new Date().getTime() + 1,
  },
  {
    id: 1,
    name: '월세',
    amount: 500000,
    type: 'expense',
    category: '🏠 생활',
    date: new Date().getTime() + 2,
  },
  {
    id: 2,
    name: '월급',
    amount: 3500000,
    type: 'income',
    category: '🏢 급여',
    date: new Date().getTime() + 3,
  },
  {
    id: 3,
    name: '스타벅스 커피',
    amount: 6500,
    type: 'expense',
    category: '☕ 카페',
    date: new Date().getTime() + 4,
  },
  {
    id: 4,
    name: '쿠팡 쇼핑',
    amount: 78000,
    type: 'expense',
    category: '🛒 쇼핑',
    date: new Date().getTime() + 5,
  },
  {
    id: 5,
    name: '프리랜서 수입',
    amount: 800000,
    type: 'income',
    category: '💻 부수입',
    date: new Date().getTime() + 6,
  },
  {
    id: 6,
    name: '헬스장 등록',
    amount: 120000,
    type: 'expense',
    category: '🏋️ 건강',
    date: new Date().getTime() + 7,
  },
  {
    id: 7,
    name: '넷플릭스 구독',
    amount: 17000,
    type: 'expense',
    category: '🎬 구독',
    date: new Date().getTime() + 8,
  },
  {
    id: 8,
    name: '친구 생일 선물',
    amount: 90000,
    type: 'expense',
    category: '🎁 기타',
    date: new Date().getTime() + 9,
  },
  {
    id: 9,
    name: '보너스',
    amount: 1200000,
    type: 'income',
    category: '💰 기타수입',
    date: new Date().getTime() + 10,
  },
];

export const CATEGORIES = ['🍚 식비', '💧 구독', '🏠 생활', '🏢 급여', '💰 금융'];
